### ISSUE TITLE
Possible to participate using Python?

### ISSUE THREAD

**Issue by ramaroesilva** [U-Shift/cyclingpotential-hack#10]
Is it okay to participate as a Python-user?

Note: I understand that it would likely imply:
- having to be able to transpose the learning from the materials to the Pythons setup,
- not getting any Python-related support from the organizers

**Comment by Robinlovelace** [comment]
:+1: from me, only aspiration is that the results of the hack are based on open source software and reproducible and I think Python is great for both of those.

**Comment by Robinlovelace** [comment]
Participation using other open source command-line tools such as Julia and Scala are also allowed, as long as the results are reproducible using open datasets, so closing this issue for now. Any other questions welcome.
